version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
- package-ecosystem: "npm"
  directory: "/app"
  schedule:
    interval: daily
    time: "13:00"
- package-ecosystem: "terraform"
  directory: "/infra"
  schedule:
    interval: daily
    time: "13:00"  