docs:
- changed-files:
  - any-glob-to-any-file:
    - examples/**
    - "**/*.md"
workflows:
- changed-files:
  - any-glob-to-any-file:
    - .github/workflows/**
infra:
- changed-files:
  - any-glob-to-any-file:
    - infra/**
app:
- changed-files:
  - any-glob-to-any-file:
    - app/**
feature:
- head-branch: ["^feature", "feature"]
fix:
- head-branch: ["^fix", "fix"]
maintenance:
- head-branch: ["^maintenance", "maintenance"]