name: Beta Build & Deploy

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: beta
      url: https://beta.weordl.com
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Build
        run: cd app && npm install && npm run build

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: weordl-prod-build
          path: app/build
          retention-days: 1

      - name: Deploy build to S3 bucket
        run: aws s3 sync app/build/ s3://${{ vars.AWS_S3_BUCKET }} --delete

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ vars.AWS_DISTRIBUTION_ID }}
          PATHS: "/*"
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}