name: Pull Request Actions (infra plan, app unit tests & checks)

on:
  pull_request:
    branches:
    - main
    - beta

jobs:
  infra:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.base_ref }}
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ vars.AWS_READ_ROLE }}
          role-session-name: github_actions_deploy_infra_weordl
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
          terraform_wrapper: false

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive

      - name: Terraform Init
        id: init
        run: terraform init -input=false -backend-config=./config/${{ github.base_ref }}.s3.tfbackend

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -out=tfplan -var-file=./config/${{ github.base_ref }}.tfvars -var='source_control=${{ github.repository }}/${{ github.base_ref }}/${{ github.sha }}'

      - name: Generate Plan Report Input
        id: show
        run: |
          terraform show -no-color tfplan > terraform.text
          terraform show -json tfplan > terraform.json

      - uses: ahmadnassri/action-terraform-report@v3
        with:
          terraform-text: ./terraform/terraform.text
          terraform-json: ./terraform/terraform.json
          show-diff: true
          github-token: ${{ github.token }}
  app:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.base_ref }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4